# -*- coding: utf-8 -*-
"""111101021_countingfail.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Sb44n3pufKneq9OAsljMKXZqZQUhQRM8
"""

score = input().split()
count = 0

for i in range(len(score)):
    if int(score[i]) < 60:
        count += 1

print("不及格人數:", count)